-- Native PostgreSQL. Applied in one transaction by scripts/migrate.ts.
CREATE TABLE IF NOT EXISTS "SchemaMigrations" (
  version integer PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM "SchemaMigrations" WHERE version=1) THEN RETURN; END IF;

  CREATE TABLE IF NOT EXISTS "Users" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL, password_hash text NOT NULL, name text NOT NULL,
    role text NOT NULL DEFAULT 'VIEWER', created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    last_login timestamptz
  );
  ALTER TABLE "Users" ALTER COLUMN role SET DEFAULT 'VIEWER';
  -- Preserve existing IDs, passwords and timestamps. Unknown roles become read-only.
  UPDATE "Users" SET role=CASE WHEN upper(role) IN ('ADMIN','DEVELOPER','OPERATOR','VIEWER') THEN upper(role) ELSE 'VIEWER' END;
  CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_username" ON "Users"(username);

  CREATE TABLE IF NOT EXISTS "Channels" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL, status text NOT NULL DEFAULT 'STOPPED',
    source_type text, source_endpoint text DEFAULT '', inbound_data_type text,
    processing_script text, response_script text, filter_script text, source_api_key text,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz
  );
  ALTER TABLE "Channels" ADD COLUMN IF NOT EXISTS source_api_key text;
  ALTER TABLE "Channels" ADD COLUMN IF NOT EXISTS filter_script text;
  ALTER TABLE "Channels" ADD COLUMN IF NOT EXISTS inbound_data_type text;
  ALTER TABLE "Channels" ALTER COLUMN status SET DEFAULT 'STOPPED';
  ALTER TABLE "Channels" ALTER COLUMN source_endpoint SET DEFAULT '';
  ALTER TABLE "Channels" ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

  CREATE TABLE IF NOT EXISTS "Destinations" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id bigint NOT NULL REFERENCES "Channels"(id), name text NOT NULL,
    type text NOT NULL, endpoint text NOT NULL, outbound_data_type text NOT NULL,
    processing_script text, response_script text, template_script text, filter_script text,
    is_enabled boolean NOT NULL DEFAULT true, is_deleted boolean NOT NULL DEFAULT false,
    retry_enabled boolean NOT NULL DEFAULT false,
    max_retries integer NOT NULL DEFAULT 3 CHECK(max_retries BETWEEN 0 AND 10),
    retry_interval_seconds integer NOT NULL DEFAULT 30 CHECK(retry_interval_seconds BETWEEN 1 AND 86400),
    timeout_ms integer NOT NULL DEFAULT 10000 CHECK(timeout_ms BETWEEN 100 AND 120000),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz
  );
  ALTER TABLE "Destinations" ADD COLUMN IF NOT EXISTS is_deleted boolean NOT NULL DEFAULT false;
  ALTER TABLE "Destinations" ADD COLUMN IF NOT EXISTS filter_script text;
  ALTER TABLE "Destinations" ADD COLUMN IF NOT EXISTS is_enabled boolean NOT NULL DEFAULT true;
  ALTER TABLE "Destinations" ADD COLUMN IF NOT EXISTS retry_enabled boolean NOT NULL DEFAULT false;
  ALTER TABLE "Destinations" ADD COLUMN IF NOT EXISTS max_retries integer NOT NULL DEFAULT 3;
  ALTER TABLE "Destinations" ADD COLUMN IF NOT EXISTS retry_interval_seconds integer NOT NULL DEFAULT 30;
  ALTER TABLE "Destinations" ADD COLUMN IF NOT EXISTS timeout_ms integer NOT NULL DEFAULT 10000;

  CREATE TABLE IF NOT EXISTS "Messages" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id bigint NOT NULL REFERENCES "Channels"(id),
    destination_id bigint REFERENCES "Destinations"(id),
    inbound_message_id bigint REFERENCES "Messages"(id),
    direction text NOT NULL CHECK(direction IN ('IN','OUT')), message_type text NOT NULL,
    original_payload text, transformed_payload text, status text NOT NULL,
    correlation_id text, dedupe_key varchar(64), transport_config text,
    retry_count integer NOT NULL DEFAULT 0, last_retry_at timestamptz, next_retry_at timestamptz,
    lease_until timestamptz, last_error text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz
  );
  ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS dedupe_key varchar(64);
  ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS destination_id bigint REFERENCES "Destinations"(id);
  ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS retry_count integer NOT NULL DEFAULT 0;
  ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS last_retry_at timestamptz;
  ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS next_retry_at timestamptz;
  ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS lease_until timestamptz;
  ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS last_error text;
  ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS correlation_id text;
  ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS transport_config text;

  CREATE TABLE IF NOT EXISTS "MessageDestinationLog" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id bigint NOT NULL REFERENCES "Messages"(id),
    destination_id bigint NOT NULL REFERENCES "Destinations"(id), status text NOT NULL,
    response_text text, request_data text, outbound_data text, ack_code text, message_control_id text,
    sent_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
  );
  ALTER TABLE "MessageDestinationLog" ADD COLUMN IF NOT EXISTS ack_code text;
  ALTER TABLE "MessageDestinationLog" ADD COLUMN IF NOT EXISTS message_control_id text;

  CREATE TABLE IF NOT EXISTS "RevokedTokens" (token_id text PRIMARY KEY, expires_at timestamptz NOT NULL);
  CREATE TABLE IF NOT EXISTS "AuditLog" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint,
    action text NOT NULL, resource_type text NOT NULL, resource_id bigint,
    request_id text NOT NULL, ip_address text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
  );
  CREATE INDEX IF NOT EXISTS "IX_Messages_monitor" ON "Messages"(direction,created_at DESC,id DESC) INCLUDE(channel_id,status,inbound_message_id);
  CREATE INDEX IF NOT EXISTS "IX_Messages_parent" ON "Messages"(inbound_message_id) INCLUDE(status,destination_id);
  CREATE INDEX IF NOT EXISTS "IX_Messages_retry" ON "Messages"(status,next_retry_at) INCLUDE(lease_until,destination_id);
  CREATE INDEX IF NOT EXISTS "IX_Messages_channel" ON "Messages"(channel_id,status,direction);
  CREATE INDEX IF NOT EXISTS "IX_DestinationLog_message" ON "MessageDestinationLog"(message_id,destination_id,sent_at DESC);
  CREATE INDEX IF NOT EXISTS "IX_Destinations_channel" ON "Destinations"(channel_id,is_enabled);
  CREATE INDEX IF NOT EXISTS "IX_Channels_status" ON "Channels"(status,source_type);
  CREATE INDEX IF NOT EXISTS "IX_Audit_created" ON "AuditLog"(created_at);
  CREATE UNIQUE INDEX IF NOT EXISTS "UX_Messages_dedupe" ON "Messages"(channel_id,dedupe_key) WHERE dedupe_key IS NOT NULL;
  INSERT INTO "SchemaMigrations"(version) VALUES(1);
END;
$migration$;
